---
- name: Test apt
  hosts: all
 
  tasks:
  - name: Remove if exist
    apt_repository: 
      repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main' 
      state: absent
    sudo: yes

  - name: Test apt 
    apt_repository: 
      repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main' 
      mode: '0700'
      state: present
    sudo: yes
